{{- if .Values.serviceMonitor.enabled }}
{{- range .Values.apiServices }}
{{- if and .enabled .expose }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "agentOps.fullname" $ }}-{{ .name }}
  labels:
    {{- include "agentOps.labels" $ | nindent 4 }}
    component: {{ .name }}
    {{- toYaml $.Values.serviceMonitor.additionalLabels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "agentOps.labels" $ | nindent 6 }}
      component: {{ .name }}
  endpoints:
    - port: http
      interval: {{ $.Values.serviceMonitor.interval }}
      scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
      path: /metrics
---
{{- end }}
{{- end }}
{{- end }}
