apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workflow-platform-secrets
  namespace: workflow-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: workflow-platform-secrets
    creationPolicy: Owner
  data:
    - secretKey: API_KEYS
      remoteRef:
        key: workflow-platform/API_KEYS
    - secretKey: JWT_SECRET
      remoteRef:
        key: workflow-platform/JWT_SECRET
