apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: kafka-trigger-auth
  namespace: workflow-platform
spec:
  # Этот ресурс нужен, когда Kafka требует аутентификацию: ScaledObject
  # может ссылаться на него и не хранить SASL-данные в явном виде в values.
  secretTargetRef:
    - parameter: sasl
      name: kafka-credentials
      key: sasl
    - parameter: username
      name: kafka-credentials
      key: username
    - parameter: password
      name: kafka-credentials
      key: password
